name = "balux-api"
main = "src/api_ops_login.ts"
compatibility_date = "2026-01-09"
workers_dev = true

routes = [
  { pattern = "api-clientesprueba.baluxvision.com/*", zone_name = "baluxvision.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "balux-database"
database_id = "16b8be5c-cba5-4c22-9401-adc8e3fa5b75"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "balux-monitor-operativa"
